version: "3.8"  # Use a valid Compose version

services:
  frontend:
    image: react-app:latest
    container_name: frontend
    build: ./frontend
    ports:
      - "3000:3000"  # Map port 3000 on the host to port 80 in the container
    volumes:
      - ./frontend:/app
      - /app/node_modules  
  
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "root"
    ports:
      - 5433:5433
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/postgresql/data
      


